Update Prometheus plugin to work with KaaF
kuzzleio/kuzzle-plugin-prometheus pull request #19
Opened 2021-04-19 09:51 UTC by Shiranuit

## What does this PR do

This PR aim to update the Prometheus Plugin to make it work with Kuzzle as a Framework
- Updated PromtheusPlugin
- Updated demo
- Updated docker-compose
- Version Bump
- Update Readme

closes #18

2021-04-19 10:29 UTC, Aschen requested changes
Good job :+1: 

Some nitpiking:
  - add blank line at the end of file
  - add a space between function declaration and first parenthesis

2021-04-19 10:29 UTC, Aschen commented on features/wait-kuzzle.sh
> +        docker-compose logs
For better CI debugging
```suggestion
        docker-compose logs
        curl http://localhost:7512?pretty
        echo "Cannot connect to Kuzzle after $tries s. Aborting."
```

2021-04-19 10:29 UTC, Aschen commented on features/fixtures/application/app.ts
> +    app.log.info('Application started')
```suggestion
    app.log.info('Application started');
```

2021-04-19 10:29 UTC, Aschen commented on lib/PrometheusPlugin.ts
> +      kuzzleVersion: '>=2.10.2 <3'
Should be updated as well

2021-04-19 10:29 UTC, Aschen commented on lib/controllers/PrometheusController.ts
> +  for (const inet in interfaces) {
This should be converted in a `for const of` loop

2021-04-19 10:29 UTC, Aschen commented on lib/controllers/PrometheusController.ts
> +  public definitions: ControllerDefinition;
Usually the controller definition is not in plural form

2021-04-19 10:29 UTC, Aschen commented on manifest.json
> +    "kuzzleVersion": ">=2.0.0 <3.0.0"
The manifest is not used anymore and can be removed

2021-04-19 10:29 UTC, Aschen commented on package.json
> +    "kuzzle": "^2",
Should be at least 2.11.0

2021-04-19 10:29 UTC, Aschen commented on package.json
> +    "kuzzle": "^2"
Should be at least 2.11.0

2021-04-20 13:39 UTC, alexandrebouthinon requested changes
You should remove the `feature` folder and Functional tests GHA for now since those are not used. Apart from that great work 👍

2021-04-20 13:39 UTC, alexandrebouthinon commented on demo/docker-compose.yml
> +
Bad indentation here

2021-04-21 09:29 UTC, alexandrebouthinon commented on README.md
>  To install this plugin on your Kuzzle stack (for each of your Kuzzle nodes):
Installation guide need to be updated to explain how to use it in a KaaF app

2021-04-21 13:40 UTC, Aschen commented on lib/controllers/PrometheusController.ts
> +  public hooks: JSONObject;
What is this used for ?

2021-04-22 14:46 UTC, Shiranuit commented on lib/controllers/PrometheusController.ts
> +  public hooks: JSONObject;
It is  only used in the PrometheusPlugin here

```typescript
  async init (config: JSONObject, context: PluginContext) {
    this.config = { ...this.defaultConfig, ...config };
    this.context = context;

    this.prometheusController = new PrometheusController(this.config, this.context);
    await this.prometheusController.init();

    this.api = {
      'prometheus': this.prometheusController.definition
    };

    this.hooks = {
      ...this.prometheusController.hooks
    };
  }
```

But I suppose I could directly add them inside the plugin since there is only one controller if that's what you meant ?

2021-04-23 10:03 UTC, alexandrebouthinon approved these changes

2021-04-23 10:03 UTC, alexandrebouthinon commented on test/mocks/config.mock.js
> +    constructor() {
Bad indent here

2021-04-23 10:03 UTC, alexandrebouthinon commented on test/mocks/request.mock.js
> +    constructor() {
Bad indent here

2021-04-23 15:12 UTC, alexandrebouthinon approved these changes

2021-04-24 08:48 UTC, Aschen commented on lib/controllers/PrometheusController.ts
> +  public hooks: JSONObject;
Actually it looks like we never add a hook, if this is the case then this property is useless.

Also, in general it's not up to a controller class to declare hooks

2021-04-24 08:51 UTC, Aschen approved these changes

2021-04-24 08:51 UTC, Aschen commented on lib/controllers/PrometheusController.ts
> +      request.response.setHeader('Content-Type', this._registry.contentType);
You should rather use the new [request.response.configure](https://docs.kuzzle.io/core/2/framework/classes/request-response/configure/) method

2021-05-05 12:15 UTC, alexandrebouthinon approved these changes

2021-05-05 12:23 UTC, alexandrebouthinon requested changes

2021-05-05 12:23 UTC, alexandrebouthinon commented on .github/workflows/push_master.workflow.yml
> +       - uses: ./.github/actions/unit-tests
Need a job to publish on NPM.js, you can find an example in the Ergol repository (https://github.com/kuzzleio/ergol/blob/8b8793b415831861c21d8c89f7e051d00bb5ef52/.github/workflows/push_master.workflow.yml#L30)

2021-05-05 12:24 UTC, rolljee requested changes

2021-05-05 12:24 UTC, rolljee commented on .github/actions/lint/action.yml
> +    - name: Install deps
This name does not reflect what's truly launch in here

2021-05-05 12:24 UTC, rolljee commented on .github/workflows/pull_request.workflow.yml
> +    runs-on: ubuntu-18.04
Nitpicking: Missing timeout property for this job

2021-05-05 12:24 UTC, rolljee commented on .github/workflows/pull_request.workflow.yml
> +     needs: [lint]
Nitpicking: Missing timeout property for this job

2021-05-05 12:24 UTC, rolljee commented on .github/workflows/push_dev.workflow.yml
> +    steps:
Nitpicking: Missing timeout property for this job

2021-05-05 12:24 UTC, rolljee commented on .github/workflows/push_dev.workflow.yml
> +     runs-on: ubuntu-18.04
Nitpicking: Missing timeout property for this job

2021-05-05 12:24 UTC, rolljee commented on .github/workflows/push_master.workflow.yml
> +    steps:
Nitpicking: Missing timeout property for this job

2021-05-07 08:43 UTC, alexandrebouthinon approved these changes

2021-05-07 12:36 UTC, rolljee approved these changes

2021-05-18 12:20 UTC, Leodau approved these changes

2021-05-18 12:44 UTC, merged