Rework Prometheus plugin to use new `server:metrics` action
kuzzleio/kuzzle-plugin-prometheus pull request #27
Opened 2021-12-16 13:09 UTC by alexandrebouthinon

2022-01-03 11:03 UTC, Aschen requested changes
Function name and first parenthesis should be separated with a single space 
```
// Example
 updateCoreMetrics (jsonMetrics: JSONObject) { ...
 ```

2022-01-03 11:03 UTC, Aschen commented on docker-compose.yml
> +      - kuzzle_server__protocols__mqtt__enabled=true
Why enable MQTT?

2022-01-03 11:03 UTC, Aschen commented on lib/PrometheusPlugin.ts
> + * @private
Why adding this flag? Isn't this type supposed to be used by anyone?

2022-01-03 11:03 UTC, Aschen commented on lib/PrometheusPlugin.ts
> +      'server:afterMetrics': async (request: KuzzleRequest) => this.guard(request, this.pipeFormatMetrics.bind(this)),
The `server:metrics` action can be used without any special format and thus be accessed from any protocol. Your guard is preventing that.

This pipe should check if a format argument has been passed with the value `prometheus` and if it's the case it should format the result.  
Also IMHO there is no reason to restrict this to the HTTP protocol. For debug purposes we may use this with WebSocket for example but the prometheus client will always use the HTTP route either way

2022-01-03 11:03 UTC, Aschen commented on lib/PrometheusPlugin.ts
> +            handler: async (request: KuzzleRequest) => this.guard(request, this.metrics.bind(this)),
I'm not sure we want to keep retro-compatibility here. Since we are releasing a major version, we should get ride of the obsolete code.  

A simple guide in the documentation should help our clients to migrate

2022-01-03 11:03 UTC, Aschen commented on lib/PrometheusPlugin.ts
> +export type PluginConfiguration = {
The type name should be explicit like `PrometheusPluginConfiguration`

2022-01-03 11:03 UTC, Aschen commented on lib/PrometheusPlugin.ts
> + * @type {PluginConfiguration}
Useless flag with typescript

2022-01-03 11:03 UTC, Aschen commented on lib/PrometheusPlugin.ts
> +    if (request.input.args['format'] || request.input.args['format'] === 'prometheus') {
Why using the `['format']` notation here ? You could rather use the `request.getString('format')` helper

2022-01-03 11:03 UTC, Aschen commented on lib/services/MetricService.ts
> +import { PluginConfiguration } from "../PrometheusPlugin";
Nitpicking: string should use single quote and external import should be separated from internal ones
```suggestion
import { JSONObject } from 'kuzzle';
import { Gauge, Registry, collectDefaultMetrics, Histogram } from 'prom-client';

import { PluginConfiguration } from '../PrometheusPlugin';
```

2022-01-10 14:55 UTC, alexandrebouthinon commented on lib/PrometheusPlugin.ts
> +      'server:afterMetrics': async (request: KuzzleRequest) => this.guard(request, this.pipeFormatMetrics.bind(this)),
Yep you're right, 6 month seems enough to me between two major version, I'll remove it

2022-01-10 15:00 UTC, alexandrebouthinon commented on lib/PrometheusPlugin.ts
> +      'server:afterMetrics': async (request: KuzzleRequest) => this.guard(request, this.pipeFormatMetrics.bind(this)),
About the HTTP only access, this was a far away demand from one of our client. It seems useless on a pipe now. I'll get rid of it

2022-01-10 15:01 UTC, alexandrebouthinon commented on docker-compose.yml
> +      - kuzzle_server__protocols__mqtt__enabled=true
This is the dev stack, it was useful to test metrics counting/formatting on multiple protocols

2022-01-10 15:01 UTC, alexandrebouthinon commented on lib/PrometheusPlugin.ts
> + * @private
IDE autofill left-over I guess

2022-01-11 06:58 UTC, Aschen requested changes

2022-01-11 06:58 UTC, Aschen commented on lib/PrometheusPlugin.ts
> +    this.metricService = new MetricService(this.config as PrometheusPluginConfiguration);
Useless cast

2022-01-11 06:58 UTC, Aschen commented on test/PrometheusPlugin.spec.ts
> +      console.log(response)
Debug leftover

2022-01-11 06:58 UTC, Aschen commented on docker-compose.yml
> +      retries: 10
This should be increased because it can take more time on slower computer (mine for example)
```suggestion
      retries: 30
```

2022-01-11 06:58 UTC, Aschen commented on config/kuzzlerc
> +    "kuzzle-plugin-prometheus": {
The plugin name is prometheus
```suggestion
    "prometheus": {
```

2022-01-11 06:58 UTC, Aschen commented on lib/services/MetricService.ts
> +  public async getMetrics(): Promise<string> {
Useless `async`

2022-01-11 06:58 UTC, Aschen commented on lib/PrometheusPlugin.ts
> +  async init(config: PrometheusPluginConfiguration, context: PluginContext) {
Nitpicking: coding standard
```suggestion
  async init (config: PrometheusPluginConfiguration, context: PluginContext) {
```

2022-01-11 06:58 UTC, Aschen commented on lib/PrometheusPlugin.ts
> +  recordRequest(request: KuzzleRequest): void {
Nitpicking: coding standard
```suggestion
  recordRequest (request: KuzzleRequest): void {
```

2022-01-11 06:58 UTC, Aschen commented on lib/services/MetricService.ts
> +  constructor(config: PrometheusPluginConfiguration) {
Nitpicking: coding standard
```suggestion
  constructor (config: PrometheusPluginConfiguration) {
```

2022-01-11 06:58 UTC, Aschen commented on lib/services/MetricService.ts
> +  public updateCoreMetrics(jsonMetrics: JSONObject): void {
Nitpicking: coding standard
```suggestion
  public updateCoreMetrics (jsonMetrics: JSONObject): void {
```

2022-01-11 06:58 UTC, Aschen commented on lib/services/MetricService.ts
> +  public async getMetrics(): Promise<string> {
Nitpicking: coding standard
```suggestion
  public async getMetrics (): Promise<string> {
```

2022-01-11 06:58 UTC, Aschen commented on lib/services/MetricService.ts
> +  public getPrometheusContentType(): string {
Nitpicking: coding standard
```suggestion
  public getPrometheusContentType (): string {
```

2022-01-11 06:58 UTC, Aschen commented on lib/services/MetricService.ts
> +  public recordResponseTime(time: number, labels: {[key: string]: string | number}): void {
Nitpicking: coding standard
```suggestion
  public recordResponseTime (time: number, labels: {[key: string]: string | number}): void {
```

2022-01-13 18:19 UTC, Aschen approved these changes
LGTM :+1:

2022-01-19 10:53 UTC, Aschen commented on package.json
> +    "test:functional": "cucumber-js --require-module ts-node/register --require features/step_definitions/*.ts --exit --fail-fast",
Nitpicking: Shorthand
```suggestion
    "test:functional": "cucumber-js -r ts-node/register --require features/step_definitions/*.ts --exit --fail-fast",
```

2022-01-20 10:11 UTC, Aschen commented on lib/PrometheusPlugin.ts
> +      // coreMetrics need to be updated with Kuzzle core values before the metrics are sent to the client
Nitpicking
```suggestion
    if ( request.getString('format', 'invalid') === 'prometheus' 
      && request.context.connection.protocol === 'http'
    ) {
      // coreMetrics need to be updated with Kuzzle core values before the metrics are sent to the client
```

2022-01-20 13:06 UTC, alexandrebouthinon commented
A dedicated documentation page will come later (with the custom metrics feature) because for now, it would just be a duplicate README.

2022-01-21 16:54 UTC, Aschen approved these changes

2022-01-21 16:55 UTC, Aschen commented
> A dedicated documentation page will come later (with the custom metrics feature) because for now, it would just be a duplicate README.

Actually it should rather be in the documentation website don't you think?

2022-01-23 21:34 UTC, alexandrebouthinon commented
> > A dedicated documentation page will come later (with the custom metrics feature) because for now, it would just be a duplicate README.
> 
> Actually it should rather be in the documentation website don't you think?

Yep I think you're right and this is the good time to init the documentation framework in this repo before we get too much doc pages to write 🙂

2022-01-24 10:01 UTC, alexandrebouthinon commented
According to our Discord discussion, the documentation will be release later at the same the custom metrics support

2022-01-25 16:51 UTC, merged